fisher update

diff --git a/.config/fish/conf.d/bin/git-forgit b/.config/fish/conf.d/bin/git-forgit
--- a/.config/fish/conf.d/bin/git-forgit
+++ b/.config/fish/conf.d/bin/git-forgit
@@ -12,27 +12,7 @@
 # This gives users the choice to set aliases inside of their git config instead
 # of their shell config if they prefer.
 
-# Check if fzf is installed
-installed_fzf_version=$(fzf --version 2>/dev/null | awk '{print $1}')
-if [[ -z "$installed_fzf_version" ]]; then
-    echo "fzf is not installed. Please install fzf first."
-    exit 1
-fi
-
-# Check fzf version
-required_fzf_version="0.49.0"
-higher_fzf_version=$(printf '%s\n' "$required_fzf_version" "$installed_fzf_version" | sort -V | tail -n1)
-if [[ "$higher_fzf_version" != "$installed_fzf_version" ]]; then
-    echo "fzf version $required_fzf_version or higher is required. You have $installed_fzf_version."
-    exit 1
-fi
-
-# Set shell for fzf preview commands
-SHELL="$(which bash)"
-export SHELL
-
-# Get absolute forgit path
-FORGIT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)/$(basename -- "${BASH_SOURCE[0]}")
+REQUIRED_FZF_VERSION="0.49.0"
 
 FORGIT_FZF_DEFAULT_OPTS="
 $FZF_DEFAULT_OPTS
@@ -252,6 +232,14 @@ _forgit_reflog() {
     return $fzf_exit_code
 }
 
+_forgit_remove_status_from_diff_line() {
+    # Remove the status prefix from a diff line, e.g.
+    #   [M]     somefile
+    # becomes
+    #   somefile
+    sed 's/^[[:space:]]*\[[A-Z0-9]*\][[:space:]]*//'
+}
+
 _forgit_get_files_from_diff_line() {
     # Construct a null-terminated list of the filenames
     # The input looks like one of these lines:
@@ -264,13 +252,13 @@ _forgit_get_files_from_diff_line() {
     #   oldfile\0
     # We have to do a two-step sed -> tr pipe because OSX's sed implementation does
     # not support the null-character directly.
-    sed 's/^[[:space:]]*\[[A-Z0-9]*\][[:space:]]*//' | sed 's/  ->  /\n/' | tr '\n' '\0'
+    _forgit_remove_status_from_diff_line | sed 's/  ->  /\n/' | tr '\n' '\0'
 }
 
 _forgit_get_single_file_from_diff_line() {
     # Similar to the function above, but only gets a single file from a single line
     # Gets the new name of renamed files
-    sed 's/^[[:space:]]*\[[A-Z0-9]*\][[:space:]]*//' | sed 's/.*->  //'
+    _forgit_remove_status_from_diff_line | sed 's/.*->  //'
 }
 
 _forgit_exec_diff() {
@@ -1185,7 +1173,54 @@ _forgit_paths_list() {
     find "$path" -name "*$ext" -print |sed -e "s#$ext\$##" -e 's#.*/##' -e '/^$/d' | sort -fu
 }
 
-public_commands=(
+check_prequisites() {
+    local installed_fzf_version
+    local higher_fzf_version
+
+    # Check if fzf is installed
+    installed_fzf_version=$(fzf --version 2>/dev/null | awk '{print $1}')
+    if [[ -z "$installed_fzf_version" ]]; then
+        echo "fzf is not installed. Please install fzf first."
+        exit 1
+    fi
+
+    # Check fzf version
+    higher_fzf_version=$(printf '%s\n' "$REQUIRED_FZF_VERSION" "$installed_fzf_version" | sort -V | tail -n1)
+    if [[ "$higher_fzf_version" != "$installed_fzf_version" ]]; then
+        echo "fzf version $REQUIRED_FZF_VERSION or higher is required. You have $installed_fzf_version."
+        exit 1
+    fi
+}
+
+main() {
+    local cmd="$1"
+    shift
+
+    check_prequisites
+
+    # Set shell for fzf preview commands
+    SHELL="$(which bash)"
+    export SHELL
+
+    # Get absolute forgit path
+    FORGIT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)/$(basename -- "${BASH_SOURCE[0]}")
+
+    # shellcheck disable=SC2076
+    if [[ ! " ${PUBLIC_COMMANDS[*]} " =~ " ${cmd} " ]] && [[ ! " ${PRIVATE_COMMANDS[*]} " =~ " ${cmd} " ]]; then
+        if [[ -z "$cmd" ]]; then
+            printf "forgit: missing command\n\n"
+        else
+            printf "forgit: '%s' is not a valid forgit command.\n\n" "$cmd"
+        fi
+        printf "The following commands are supported:\n"
+        printf "\t%s\n" "${PUBLIC_COMMANDS[@]}"
+        exit 1
+    fi
+
+    _forgit_"${cmd}" "$@"
+}
+
+PUBLIC_COMMANDS=(
     "add"
     "attributes"
     "blame"
@@ -1212,7 +1247,7 @@ public_commands=(
     "stash_push"
 )
 
-private_commands=(
+PRIVATE_COMMANDS=(
     "add_preview"
     "blame_preview"
     "branch_preview"
@@ -1243,19 +1278,10 @@ private_commands=(
     "pager"
 )
 
-cmd="$1"
-shift
-
-# shellcheck disable=SC2076
-if [[ ! " ${public_commands[*]} " =~ " ${cmd} " ]] && [[ ! " ${private_commands[*]} " =~ " ${cmd} " ]]; then
-    if [[ -z "$cmd" ]]; then
-        printf "forgit: missing command\n\n"
-    else
-        printf "forgit: '%s' is not a valid forgit command.\n\n" "$cmd"
-    fi
-    printf "The following commands are supported:\n"
-    printf "\t%s\n" "${public_commands[@]}"
-    exit 1
+# Check if the script is being sourced. This is necessary for unit tests where
+# we do not want to execute the main function.
+if [[ "${BASH_SOURCE[0]}" != "$0" ]]; then
+    return 0
 fi
 
-_forgit_"${cmd}" "$@"
+main "${@}"
